"""
Django settings for inventarioBE project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta #para configurar el tiempo de expiracion del token

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w48xdp^cgw-292)34h^1udou4g6i3+()fm)0xvchyfn^*j%!z$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Definir el modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'


ALLOWED_HOSTS = []


#Configuracion de CORS
CORS_ALLOW_ALL_ORIGINS = True

#configuracion de session para que no de error al usar SessionAuthentication
CORS_ALL_CREDENTIALS = True

# Definir el modelo de usuario personalizado
#AUTH_USER_MODEL = "usuarios.Usuario"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apis
    'rest_framework',
    
    #cors
    "corsheaders",
    #token
    "rest_framework_simplejwt",
    #contraseña olvidada
    'django_rest_passwordreset',  

    # Apps
    'apps.usuarios',
    'apps.productos',
    'apps.inventarios',
    'apps.garantias',
    'apps.clientes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventarioBE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventarioBE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Configuracion para rest framework

REST_FRAMEWORK = {
    #filtar de forma sencilla
    "DEFAULT_FILTER_BACKENDS": [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    
    #trabajar con autenticacion por token
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    
    #definir permisos globales
    "DEFAULT_PERMISSION_CLASSES": [
        'rest_framework.permissions.IsAuthenticated', #solo usuarios autenticados
    ],

}


# Configuracion para JWT por tiempo de expiracion
SIMPLE_JWT = {
    #Token de acceso que se utiliza en  cada peticion
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Token de acceso dura 15 min
    #Duracion del token de refresco (sirve para obtener un nuevo token de acceso sin necesidad de loguearse)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Token de refresco dura 1 día
    
    'ROTATE_REFRESH_TOKENS': True,                  # Renovar refresh token
    'BLACKLIST_AFTER_ROTATION': True,               # Invalidar token anterior
    "AUTH_HEADER_TYPES": ("Bearer",),  # Tipo de token en el header Authorization
}

#configuracion para enviar correos

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "powerstock2025@gmail.com"
EMAIL_HOST_PASSWORD = "vttd tdgb vgxb aumn"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
