"""
Django settings for inventarioBE project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta #para configurar el tiempo de expiracion del token
from decouple import config #para manejar credenciales en github
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-w48xdp^cgw-292)34h^1udou4g6i3+()fm)0xvchyfn^*j%!z$'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-w48xdp^cgw-292)34h^1udou4g6i3+()fm)0xvchyfn^*j%!z$"
)

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com"]


# Definir el modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'


#ALLOWED_HOSTS = []


#Configuracion de CORS
CORS_ALLOW_ALL_ORIGINS = True

#configuracion de session para que no de error al usar SessionAuthentication
CORS_ALL_CREDENTIALS = True

# Definir el modelo de usuario personalizado
#AUTH_USER_MODEL = "usuarios.Usuario"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apis
    'rest_framework',
    
    #cors
    "corsheaders",
    #token
    "rest_framework_simplejwt",
    #recuperacion de contraseña
    'django.contrib.sites',  
    'django_rest_passwordreset',  
    
    #implementar OAuth
    'social_django',

    # Apps
    'apps.usuarios',
    'apps.productos',
    'apps.inventarios.apps.InventariosConfig',
    'apps.garantias',
    'apps.clientes',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Cors Headers Middleware
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    

]

ROOT_URLCONF = 'inventarioBE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventarioBE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'CONN_MAX_AGE': 600,  # mantiene conexiones abiertas para mejor rendimiento
        'OPTIONS': {
            'sslmode': 'require',  # importante para Neon
        },
    }
}'''

'''DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "inventario",      # nombre de tu base de datos
        "USER": "postgres",           # usuario de postgres (o el que uses)
        "PASSWORD": "1234",  # la contraseña de ese usuario
        "HOST": "localhost",
        "PORT": "5432",
    }
}'''

# Database
# Usamos siempre DATABASE_URL desde variables de entorno
DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default="postgres://postgres:1234@localhost:5432/inventario"),
        conn_max_age=600,
    )
}



STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Configuracion para rest framework

REST_FRAMEWORK = {
    #filtar de forma sencilla
    "DEFAULT_FILTER_BACKENDS": [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    
    #trabajar con autenticacion por token
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    
    #definir permisos globales
    "DEFAULT_PERMISSION_CLASSES": [
        'rest_framework.permissions.IsAuthenticated', #solo usuarios autenticados
    ],

}





# Configuracion para JWT por tiempo de expiracion
SIMPLE_JWT = {
    #Token de acceso que se utiliza en  cada peticion
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=35),  # Token de acceso dura 35 min
    #Duracion del token de refresco (sirve para obtener un nuevo token de acceso sin necesidad de loguearse)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Token de refresco dura 1 día
    
    'ROTATE_REFRESH_TOKENS': True,                  # Renovar refresh token
    'BLACKLIST_AFTER_ROTATION': True,               # Invalidar token anterior
    "AUTH_HEADER_TYPES": ("Bearer",),  # Tipo de token en el header Authorization
}

#configuracion para enviar correos

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH2_SECRET')

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True # Permitir todas las origines (para desarrollo)

# URL de redirección en caso de error durante el login por OAuth y no encuentra usuario en la BD
SOCIAL_AUTH_LOGIN_ERROR_URL = "http://localhost:5173/?error=oauth"


AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',   # para Google
    'django.contrib.auth.backends.ModelBackend',  # login normal
)


#  Pipeline (para ejecutar nuestra lógica al crear usuario)
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.user.get_username',
    'apps.usuarios.pipelines.associate_by_email', 
    'social_core.pipeline.social_auth.social_user',

    
    'social_core.pipeline.user.create_user',
    
    'apps.usuarios.pipelines.asignar_rol_por_defecto',

    'apps.usuarios.pipelines.associate_user_safe',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'apps.usuarios.pipelines.save_profile',
    'apps.usuarios.pipelines.create_jwt_token_with_role',
    'apps.usuarios.pipelines.social_user_safe',
    
)

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


SOCIAL_AUTH_RAISE_EXCEPTIONS = False


TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
TELEGRAM_DEFAULT_CHAT_ID = config("TELEGRAM_DEFAULT_CHAT_ID")

