# Generated by Django 5.2.6 on 2025-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='notificado_sin_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='notificado_stock_bajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
