# Generated by Django 5.2.6 on 2025-11-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='cliente',
            field=models.CharField(default='Sin cliente', max_length=600),
        ),
    ]
