# Generated by Django 5.2.6 on 2025-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='notificada_por_vencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garantia',
            name='notificada_vencida',
            field=models.BooleanField(default=False),
        ),
    ]
