# Generated by Django 5.2.6 on 2025-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0002_garantia_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
