# Generated by Django 5.2.6 on 2025-11-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0002_garantia_notificada_por_vencer_and_more'),
        ('garantias', '0003_garantia_telefono_cliente'),
    ]

    operations = [
    ]
