# Generated by Django 5.2.6 on 2025-11-15 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='productos',
            field=models.ManyToManyField(related_name='inventarios', through='inventarios.InventarioProducto', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='inventarios.loteinventario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.tipoinventario'),
        ),
    ]
