# Generated by Django 5.2.6 on 2025-11-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='auditoria',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
