# Generated by Django 5.2.6 on 2025-10-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_inventario_stock_anterior'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='diferencias_encontrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='productos',
            field=models.ManyToManyField(related_name='inventarios', through='inventarios.InventarioProducto', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='num_diferencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ventas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
