# Generated by Django 5.2.6 on 2025-11-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_inventario_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='auditoria',
        ),
    ]
