# Generated by Django 5.2.6 on 2025-10-11 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_inventario_diferencias_encontrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
