# Generated by Django 5.2.6 on 2025-10-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_initial'),
        ('inventarios', '0004_remove_inventarioproducto_fecha_creacion_and_more'),
    ]

    operations = [
    ]
