# Generated by Django 5.2.6 on 2025-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('numero_telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
